### ISSUE TITLE
Accounts and External Accounts are not available

### ISSUE THREAD

**Issue by musfiqurcse** [sikanhe/stripe-elixir#1]
[Accounts](https://stripe.com/docs/api/ruby#account) and [External Accounts](https://stripe.com/docs/api/ruby#external_accounts)  are not added in this elixir client library. Moreover, the **Relay Resources(e.g Order, Return , Product)** are also not available in this library

**Comment by sikanhe** [comment]
Yes, Relay options hasn't been added because few people needed it yet, so it was pushed back. For accounts I will added it today. Do you need relay features asap ?

**Comment by sikanhe** [comment]
added in 0.4.0
