### ISSUE TITLE
usage issue

### ISSUE THREAD

**Issue by benonymus** [sikanhe/stripe-elixir#30]
Hey It might sound a bit dumb, but I am trying to learn elixir and migrating an app to phoenix background and I need stripe, and I can't seem to find examples really that where would the payment happen, in the controller? 
I get the data for the payment in my params and I think I need to cast them, and I have my schema but I how do i get back the casted value to make the call to create a customer?

Many thanks if you read this :D

**Comment by tngan** [comment]
@benonymus I think it is not an issue related to this library. You can take a look into the code, and you can see the customer creation is just a wrapper of the Stripe API call.

Therefore, you can simply call the function to create the customer.

```ex
Stripe.Customer.create(%{
  # the parameters needed to create a customer
})
```

You can check the parameters in Stripe documentation.
