### ISSUE TITLE
Request to take over maintainership

### ISSUE THREAD

**Issue by jimsynz** [sikanhe/stripe-elixir#34]
Hi @sikanhe.

We ([Narrative](https://github.com/NarrativeApp/)) have been maintaining our own fork of this stripe library for some time in which we have been making improvements as we've needed them.  I notice that there have been no updates to it since December 2017 - so I am wondering if you'd be amenable to transferring maintainership over to us?  Personally, I'm keen for the improvements we've made to get back to the community.

Thanks for all the code.  We really do appreciate it.

:heart:

**Comment by sikanhe** [comment]
hi @jimsynz I am happy to hand over the ownership of this repo, what is your email?

**Comment by jimsynz** [comment]
You mean for hex? Use hello@narrative.so
If you mean the repo then just transfer ownership to the `NarrativeApp` organisation please.

**Comment by sikanhe** [comment]
@jimsynz I tried to xfer but there is already a repo exist with the same name, and i dont have permission to create repo on your org - so I invited you as a collaborator

**Comment by sikanhe** [comment]
Hopefully then you can xfer it to your org

**Comment by jimsynz** [comment]
Thanks!

**Comment by jimsynz** [comment]
Just an update here - we're working though a maintenance backlog at the moment, so we'll get to this soon.

**Comment by Rio517** [comment]
@jimsynz Any updates?

Maybe you can update the readme/ or GitHub description with an update so others know what the maintenance looks like?

**Comment by jimsynz** [comment]
Hey folks. Sorry for the delay. We're still slammed. I was thinking it may be worth just switching to [stripity_stripe](https://github.com/code-corps/stripity_stripe) because it seems to have much more active maintainers. Thoughts?
